# Generated by Django 4.2.7 on 2023-12-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN', 'Loan'), ('LOAN_PAID', 'Loan Paid')], null=True),
        ),
    ]
